# Generated by Django 4.0.3 on 2022-10-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_all',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
